### ISSUE TITLE
Mirror container setup

### ISSUE THREAD

**Issue by scriptjs** [chrisurwin/may2016-demo#1]
I reviewed the youtube Rancher meetup on May 26 but find a couple things missing that are necessary in recreating the setup. Can you provide some details on the mirror vm you set up, preferably with a means to verify it is properly mirroring the external registry. I am assuming this a v2 registry.

Also curious why you did not use vagrant where you were using vms. This would have provided much greater simplicity in reproducing this for others in your org and for demonstration purposes. Am currently working setting this up atm.

Also looking at how much of this is necessary in vms as it is. Currently I am on OSX native docker beta so there may be little use for vms at all. You can include the local machine as a host for a Rancher install and should be able to run and trigger projects directly for Jenkins builds without the need for virtualbox.

**Comment by chrisurwin** [comment]
I used virtualbox as not everyone has access to Docker for Mac(windows) so wanted people to be able to replicate it. As I stated its really more of a showing what is possible rather than a prescriptive solution, so if you get it working with Docker for x...great. Docker for x also comes with its own little challenges such as setting a static ip...

In order to get the registry working I'm assuming you have created your machines as described at http://rancher.com/running-rancher-on-a-laptop/

Create the mirror and ensure that it has a static ip address. On the mirror host create file called **/var/lib/boot2docker/config.yml** and put the following in it:

```
version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxy:
    remoteurl: https://registry-1.docker.io
```

Then run the following command:
`docker run -d -v /var/lib/boot2docker/config.yml:/etc/docker/registry/config.yml --restart=always -p 5000:5000 -e STANDALONE=false -e MIRROR_SOURCE=https://registry-1.docker.io -e MIRROR_SOURCE_INDEX=https://index.docker.io --name registry distribution/registry:2`

This will now act as the mirror to docker hub.

On each host that you want to access the mirror add **--registry-mirror=http://mirror_ip_address:5000** to the EXTRA_ARGS in **/var/lib/boot2docker/profile**

The only testing i've ever done is to pull pull a large image down once, and then pulling it again and it should be an order of magnitude faster.
